services:
  redis:
    image: redis:7.0
    container_name: redis_service
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - red1
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

networks:
  red1:
    external: true
