#TODO://LISTO// manejar el versionado
services:
  ms-compras:
    build:
      context: .
    image: ms-compras:v1.1
    container_name: ms_compra
    environment:
      - FLASK_ENV=${FLASK_ENV}        #cambiar según el entorno a usar (development/production)
      # Configuración de PostgreSQL
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=ecomercedb
      - POSTGRES_PORT=${POSTGRES_PORT}
      # Configuración de Redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    restart: always
    volumes:
      - ./src:/app  # Sincroniza tu carpeta local con la del contenedor
    networks:
      - red1
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-compras.rule=Host(`compras.localhost`) && PathPrefix(`/api/v1`)"
      - "traefik.http.services.ms-compras.loadbalancer.server.port=5000"

networks:
  red1:
    external: true  # Usa la red compartida para la base de datos y redis
